defaults:
  - trainer: defaults
  - optimizer: adam
  - experiment: ???
  - server: ???
  - resume_overrides: no_overrides
data:
  n_steps_input: 4
  n_steps_output: 1
# model:
#   gradient_checkpointing: False
data_workers: 14
wandb_project_name: "the_well_extended_again"
